export const GET_LATEST_TOURS = "GET_LATEST_TOURS";
export const START_LOADING = "START_LOADING";
export const LOG_ERROR = "LOG_ERROR";
export const GET_FIRS_PAGE_PICTURES = "GET_FIRS_PAGE_PICTURES";
export const GET_FIRST_PAGE_DATA = "GET_FIRST_PAGE_DATA";
export const SEARCH_RESULT = "SEARCH_RESULT";
